# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ps_emio.xdc

# Block Designs: bd/ps_emio/ps_emio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_emio || ORIG_REF_NAME==ps_emio} -quiet] -quiet

# IP: bd/ps_emio/ip/ps_emio_processing_system7_0_0/ps_emio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_emio_processing_system7_0_0 || ORIG_REF_NAME==ps_emio_processing_system7_0_0} -quiet] -quiet

# XDC: d:/WorkSpace/Vivado/ps_emio_clg400/ps_emio_clg400.gen/sources_1/bd/ps_emio/ps_emio_ooc.xdc
