# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkSpace/Vivado/ps_emio_clg400/ps_emio_clg400.srcs/sources_1/bd/ps_emio/ip/ps_emio_processing_system7_0_0/ps_emio_processing_system7_0_0.xci
# IP: The module: 'ps_emio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/Vivado/ps_emio_clg400/ps_emio_clg400.gen/sources_1/bd/ps_emio/ip/ps_emio_processing_system7_0_0/ps_emio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_emio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/WorkSpace/Vivado/ps_emio_clg400/ps_emio_clg400.srcs/sources_1/bd/ps_emio/ip/ps_emio_processing_system7_0_0/ps_emio_processing_system7_0_0.xci
# IP: The module: 'ps_emio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/Vivado/ps_emio_clg400/ps_emio_clg400.gen/sources_1/bd/ps_emio/ip/ps_emio_processing_system7_0_0/ps_emio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_emio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
